name: CI Test

on: pull_request

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    container: openjdk:17

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build & Test with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
